## docker-compose.yml

version: "3.9"

services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./models:/train/models

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    depends_on:
      - trainer
